/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ApplicationLogo: typeof import('./src/components/ApplicationLogo.vue')['default']
    Card: typeof import('./src/components/Card.vue')['default']
    Dialog: typeof import('./src/components/shared/Dialog.vue')['default']
    DropDown: typeof import('./src/components/common/DropDown.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRate: typeof import('element-plus/es')['ElRate']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElText: typeof import('element-plus/es')['ElText']
    Filter: typeof import('./src/components/shared/Filter.vue')['default']
    LandingScreen: typeof import('./src/components/Home/LandingScreen.vue')['default']
    LoginForm: typeof import('./src/components/Auth/LoginForm.vue')['default']
    Logo: typeof import('./src/components/common/Logo.vue')['default']
    MovieCard: typeof import('./src/components/common/MovieCard.vue')['default']
    MovieInfo: typeof import('./src/components/MovieDetails/MovieInfo.vue')['default']
    MovieLister: typeof import('./src/components/shared/MovieLister.vue')['default']
    MoviesList: typeof import('./src/components/Movies/MoviesList.vue')['default']
    ProfileHeader: typeof import('./src/components/Profile/ProfileHeader.vue')['default']
    RecommandedMoviesList: typeof import('./src/components/Home/RecommandedMoviesList.vue')['default']
    RegisterForm: typeof import('./src/components/Auth/RegisterForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SimilarMovies: typeof import('./src/components/MovieDetails/SimilarMovies.vue')['default']
    TrendingMovies: typeof import('./src/components/Home/TrendingMovies.vue')['default']
    VideoContainer: typeof import('./src/components/MovieDetails/VideoContainer.vue')['default']
  }
}
