/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ApplicationLogo: typeof import('./src/components/ApplicationLogo.vue')['default']
    Card: typeof import('./src/components/Card.vue')['default']
    DropDown: typeof import('./src/components/common/DropDown.vue')['default']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    LandingScreen: typeof import('./src/components/Home/LandingScreen.vue')['default']
    LoginForm: typeof import('./src/components/Login/LoginForm.vue')['default']
    MovieDetail: typeof import('./src/components/Movie-Detail.vue')['default']
    RecommandedMovies: typeof import('./src/components/Home/RecommandedMovies.vue')['default']
    RecommandedMoviesList: typeof import('./src/components/Home/RecommandedMoviesList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
