/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ApplicationLogo: typeof import('./src/components/ApplicationLogo.vue')['default']
    Card: typeof import('./src/components/Card.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    LandingScreen: typeof import('./src/components/Home/LandingScreen.vue')['default']
    LoginForm: typeof import('./src/components/Login/LoginForm.vue')['default']
    MovieDetail: typeof import('./src/components/Movie-Detail.vue')['default']
    RecommandedMovieCard: typeof import('./src/components/Home/RecommandedMovieCard.vue')['default']
    RecommandedMovieList: typeof import('./src/components/Home/RecommandedMovieList.vue')['default']
    RecommandedMovies: typeof import('./src/components/Home/RecommandedMovies.vue')['default']
    RecommandedMoviesList: typeof import('./src/components/Home/RecommandedMoviesList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
