export const genres = [
    { name: 'Action', id: 1 },
    { name: 'Adventure', id: 2 },
    { name: 'Animation', id: 3 },
    { name: 'Comedy', id: 4 },
    { name: 'Crime', id: 5 },
    { name: 'Documentary', id: 6 },
    { name: 'Drama', id: 7 },
    { name: 'Family', id: 8 },
    { name: 'Fantasy', id: 9 },
    { name: 'History', id: 10 },
    { name: 'Horror', id: 11 },
    { name: 'Music', id: 12 },
    { name: 'Mystery', id: 13 },
    { name: 'Romance', id: 14 },
    { name: 'Science Fiction', id: 15 },
    { name: 'TV Movie', id: 16 },
    { name: 'Thriller', id: 17 },
    { name: 'War', id: 18 },
    { name: 'Western', id: 19 },
]